[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
//Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

//* underlying business goals, essential features and functional requirements for the system
//* quality goals for the architecture
//* relevant stakeholders and their expectations

The system, DeDe, is this year's project for the course Software Architecture of the University of Oviedo. The development team, that is, the team EN1B is composed of the following students:

* Alonso Ferreiro, Luis Miguel.
* Álvarez Díaz, Daniel.
* Cuesta Martínez, Miguel.
* González Méndez, Jesús.
* López Hernández, Sebastián.

And, of course, of the teacher:

* Labra Gayo, Jose Emilio.

DeDe is a online retail system that preserves the privacy of the customers following the SOLID principles. This means that our Decentralized Delivery app will not store user data per se, but will acess, when permission is granted, the information located inside the user's SOLID pod. This information will be used by our app to know the user's address for delivery purposes.

****

=== Requirements Overview

[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
//From the point of view of the end users a system is created or modified to
//improve support of a business activity and/or improve the quality.
The main point of creating DeDe is to develop a delivery application similar to those that already exist, but which does not store user data in the app's database. Instead, user hosted SOLID pods will be used.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| _<Role-1>_ | _<Contact-1>_ | _<Expectation-1>_
| _<Role-2>_ | _<Contact-2>_ | _<Expectation-2>_
|===
