[[section-runtime-view]]
== Runtime View

=== User browses DeDe WebApp
* When a user enters DeDe's WebApp (s)he can browse through it. Several items are displayed
organized following some policy, such as category (type of item). Such item will display an image and price.

[plantuml,"User browses DeDe",png]
----
actor User
participant WebApp
participant DeDe_Server
database DB as "DeDe database"
User -> WebApp: Enters WebApp

WebApp -> DeDe_Server: Index Request
DeDe_Server -> DB: Asks for items in stock
DB --> DeDe_Server: Returns items in stock
DeDe_Server --> WebApp: Returns content displaying several items and principal page
WebApp --> User: Shows webpage
----

=== User makes an order
* For the purpose of making an order, the user should select some item(s). The cumulative price of the items in the order will be shown. (Users should be notified that delivery costs are not included yet).
When the user decides to proceed with the ordering, a registration is made.
The system gets the delivery address from the user's own POD. 
The price is calculated using an API and taking into account the distance
from the distribution center to that address.
If the user decides to finish with the ordering, the registration is made and 
the order is done.

[plantuml,"Runtimeview 2",png]
----
actor User
participant WebApp
participant DeDe_Server
database DB as "DeDe database"
database POD as "User's POD"
User -> WebApp: Selects item

WebApp -> DeDe_Server: Ask for price and information related to item selected
DeDe_Server -> DB: Manages users request
DB --> DeDe_Server: Returns price of item and more info
DeDe_Server --> WebApp: Returns content displaying user's request
WebApp --> User: displays content requested
User -> WebApp: approves ordering process
WebApp --> DeDe_Server: notifies of user's decision
DeDe_Server -> POD: asks delivery address
POD --> DeDe_Server: returns delivery address
DeDe_Server -> DeDe_Server:calculates price based on distance
DeDe_Server --> WebApp: notifies of total price (delivery costs included)
WebApp --> User: shows order's total price
User -> WebApp: decides to continue (assuming costs)
WebApp -> DeDe_Server: notifies registration of order
DeDe_Server -> DB: registers order number and order's metainf
DeDe_Server -> DB: updates stock of items
DeDe_Server --> WebApp: notifies of ordering process completion
WebApp --> User: notifies finalization of ordering
----


=== User logs in
 * To log in, the user must access the login page, where they must choose a solid pod provider to authenticate with. Once authentication is complete, the provider will grant the web app the information requested. Thanks to this information, the user orders stored in the database will be retrieved. All this data will be shown to the user by means of the user page.

[plantuml,"Runtimeview 3",png]
----
@startuml 07_RuntimeView_login
actor User
participant WebApp
participant restapi as "Dede Server"
participant Provider as "Pod Provider"
database POD as "User's POD"
database DB as "DeDe database"

User -> WebApp: Selects provider
WebApp -> Provider: Asks for login
Provider -> POD: Searches for login information
POD -> Provider: Returns login information
Provider -> WebApp: Returns login information
WebApp -> restapi: Asks for user orders
restapi -> DB: Asks for user orders
DB -> restapi: Returns user orders
restapi -> WebApp: Returns user orders
WebApp -> User: Shows user profile page

@enduml
----































