[[section-concepts]]
== Cross-cutting Concepts
=== Domain model
* User, will use the unique id of the user's pod, which will provide us the different addresses that the user has available.
As well as the role assigned to the user.

We will store store the user in our non-relational database, provided by mongoDB.

=== Design patterns 
The MVC pattern is the one that will be used to start coding our  project, as it is one of the best ways for accessing the SOLID pods using REACT. 

Routes for accessing every action will exist, and a model defining the database schema will be defined.

=== Security
Protocol HTTPS will be used to ensure the user's secure access, and validation constraints will be present to avoid undesired access.

SOLID pods also provide a mean of security, as each user is the only owner of his/her private information stored in a decentralised way.

=== Technical decisions
An independent login was used to access the administrator page, we considered this decision a mean of improving security on that specific feature, as there will be only one administrator and we don't want to depend on external providers for performing any of its responsabilities.

=== Internationalization
[.line-through]#The project will be a multi-language application since the beginning of the design, to save expensive future costs in implementing this functionality.#

Unfortunately, due to time constraints, the interationalization of the app could not be implemented. DedEx remains a single language application for the moment, written entirely en English.

=== Notifications
[.line-through]#A notification system will be implemented, in which a user gets a notification that provides relevant information to keep track of the product, such as whether that product has arrived or not.#

On the same trend as with internazionalization, time would not let us implement this optional feature. Both these things are now pending to create in next sprints.


