[[section-concepts]]
== Cross-cutting Concepts
=== Domain model
* User, will use the unique id of the users pod, which will provide us the different addresses that the user has available.
As well as the role assigned to the user.

We will store store the user in our non-relational database, provided by mongoDB.

=== Design patterns 
The MVC pattern is the one that will be used to start coding our  project, as it is one of the best ways for accessing the SOLID pods using REACT. 

Routes for accessing every action will exist, and a model defining the database skeleton will be defined.

=== Security
Protocol HTTPS will be used to ensure the user's secure access, and validation constraints will be present to avoid undesired access.

SOLID pods also provide a mean od security, as each user has it's own information protected using the authentication SOLID library.

=== Technical decisions
(Still undecided)

=== Internationalization
the project will be a multi-language application since the beginning of the design, to save expensive future costs in implementing this functionality.

=== Notifications
A notification system will be implemented, in which an user gets a notification that provides relevatn information to keep track of the product or if that product has arrived.


