[[section-design-decisions]]
== Design Decisions


=== Web Application
We decided to create a Web application supported by the latest versions of the main market browsers (Chrome, Firefox, Edge...). This online version of DeDe could be ported
to a portable device app easily with REACT Native, a JavaScript framework for writing real, natively rendering mobile applications for iOS and Android.


=== Database
We chose MongoDB as our Database Management System because its flexible schema allows us 
to rapidly model the domain and change it with the evolution of the app without any problems.
MongoDB stores data in form of JSON so the conversion and interaction between typescript and the database are flawless.
Another point in favor is its performance and scalability although in a small application like ours is not strictly necessary.


=== Material UI
Material UI is a free React-compatible library directed at easy creation of responsive components. It contains many default styles for typography, forms, buttons, navigation, and other interface components. It will allow us to create a good frontend with less effort.
