[[section-design-decisions]]
== Design Decisions


=== Web Application
We decided to create a Web application supported by the latest versions of the main market browsers (Chrome, Firefox, Edge...). This online version of DeDe could be ported
to a portable device app easily with REACT Native, a JavaScript framework for writing real, natively rendering mobile applications for iOS and Android.


=== Database
We chose MongoDB as our Database Management System because its flexible schema allows us 
to rapidly model the domain and change it with the evolution of the app without any problems.
MongoDB stores data in form of JSON so the conversion and interaction between typescript and the database are flawless.
Another point in favor is its performance and scalability although in a small application like ours is not strictly necessary.

MongoDB is a document-oriented NoSQL database used for high volume data storage. Instead of using tables and rows as in the traditional relational databases, MongoDB makes use of collections and documents. Documents consist of key-value pairs which are the basic unit of data in MongoDB. Collections contain sets of documents and function which is the equivalent of relational database tables. MongoDB is a database which came into light around the mid-2000s.


=== Bootstrap
Bootstrap is a free and open-source CSS framework directed at responsive, mobile-first front-end web development. It contains CSS and (optionally) JavaScript-based design templates for typography, forms, buttons, navigation, and other interface components. It will allow us to create a good frontend with less effort.
